sonar.projectKey=hospital-devops
sonar.projectName=Hospital DevOps
sonar.projectVersion=1.0

sonar.sources=backend,frontend
sonar.exclusions=node_modules/**

# sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info